### ISSUE TITLE
I can't re-run a previous perfect train_nmt.py

### ISSUE THREAD

**Issue by amirj** [kyunghyuncho/dl4mt-material#49]
I had trained a NMT network about one month ago, it was great. 
Today, I can't run the same code for the same dataset. Here is the output:

`Loading data
Building model
Buliding sampler
Building f_log_probs... Done
Building f_cost... Done
Computing gradient... Done
Building optimizers... Done
Optimization
Traceback (most recent call last):
  File "train_nmt.py", line 54, in <module>
    'learning-rate': [0.001]})
  File "train_nmt.py", line 33, in main
    use_dropout=params['use-dropout'][0])
  File "/Users/AmirHJ/projects/deep-learning/seq2seq/nmt2.py", line 1176, in train
    cost = f_grad_shared(x, x_mask, y, y_mask)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 871, in **call**
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 859, in **call**
    outputs = self.fn()
ValueError: all the input array dimensions except for the concatenation axis must match exactly
Apply node that caused the error: Join(TensorConstant{0}, InplaceDimShuffle{x,0,1,2}.0, InplaceDimShuffle{x,0,1,2}.0, InplaceDimShuffle{x,0,1,2}.0)
Toposort index: 999
Inputs types: [TensorType(int8, scalar), TensorType(float32, (True, False, False, False)), TensorType(float32, (True, False, False, False)), TensorType(float32, (True, False, False, False))]
Inputs shapes: [(), (1, 26, 32, 200), (1, 26, 32, 400), (1, 26, 32, 24)]
Inputs strides: [(), (665600, 25600, 800, 4), (1331200, 51200, 1600, 4), (79872, 3072, 96, 4)]
Inputs values: [array(0, dtype=int8), 'not shown', 'not shown', 'not shown']
Outputs clients: [[InplaceDimShuffle{0,1,2,3}(Join.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "train_nmt.py", line 54, in <module>
    'learning-rate': [0.001]})
  File "train_nmt.py", line 33, in main
    use_dropout=params['use-dropout'][0])
  File "/Users/AmirHJ/projects/deep-learning/seq2seq/nmt2.py", line 1076, in train
    build_model(tparams, model_options)
  File "/Users/AmirHJ/projects/deep-learning/seq2seq/nmt2.py", line 639, in build_model
    prefix='ff_logit_lstm', activ='linear')
  File "/Users/AmirHJ/projects/deep-learning/seq2seq/nmt2.py", line 220, in fflayer
    tensor.dot(state_below, tparams[_p(prefix, 'W')]) +

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True`

**Comment by kyunghyuncho** [comment]
Can you clone the whole repository again and try it out on the repo rather than on your own directory?

**Comment by amirj** [comment]
Excuse me, this was a bug in my local development. Thank you.
